### PR TITLE
direct flatten files versions export and download

### PR DESCRIPTION
**Pull request by yolile**

### CODE REVIEW

**Comment by jpmckinney** [comment]
Why do you remove the option to download specific years?

**Comment by yolile** [comment]
> Why do you remove the option to download specific years?

I didn't, I just changed the logic for asking for the format and returning the available years for each format as I anticipate that for some years and datasets, we will only have data in JSON and not in Excel/CSV.

**Comment by jpmckinney** [comment]
Aha, yes, I see it's moved now.

**Comment by jpmckinney** [comment]
Superseded by #235

**Pull request closed without merging**
