### PR TITLE
96 full name country

### LINKED ISSUE #96: Full-name country filter (was: Landing pages per country)
During a demo to the OCP team, they asked whether it was possible to list all publications for a specific country.

I suppose we have a few options:

* Have landing pages per country, e.g. `/country/mx`, and otherwise use a similar layout to the search page.
* Change the letter filter to a country filter.
  * The filter should be reflected in the URL (query string or fragment), so that we can share links.
* Do nothing. Users can select the starting letter.

cc @sabahfromlondon

### PR DESCRIPTION
**Pull request by yolile**
closes #96

### CODE REVIEW

**Comment by yolile** [comment]
@jpmckinney note that I took the simpler approach here, but maybe we want a search box and return the country names as a separate service from the backend, instead of the current approach of having the list of country names as a dropdown

**Review by jpmckinney — APPROVED** [review]
I made a couple fixes directly.

**Comment by jpmckinney** [comment]
> @jpmckinney note that I took the simpler approach here, but maybe we want a search box and return the country names as a separate service from the backend, instead of the current approach of having the list of country names as a dropdown

I prefer making all options visible, like with a dropdown. We can maybe consider making the dropdown searchable, but it feels okay to me to scan an alphabetical list.

**Comment by yolile** [comment]
Thanks, sharing here what the dropdown looks like now, for reference
image

Do you think we should indicate somewhere what the numbers beside each country name are or is it obvious? 

From the issue, you also said:

> We can decide whether to have an info icon and tooltip to explain that unlisted countries have no datasets (that is the only reason I can think of for using letters).

Maybe we could include the tooltip with the explanation about missing countries and the number of datasets

**Comment by jpmckinney** [comment]
We have numbers next to all the other facets. If there's a UX issue, it's widespread (beyond this PR).

You can open a new issue about the tooltip. There are several issues that can be closed at once, when tooltips are implemented.

**Pull request merged**
